# Generated by Django 5.1.4 on 2025-04-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GuestAccount",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=32)),
                (
                    "loginType",
                    models.CharField(default="guest", editable=False, max_length=16),
                ),
            ],
            options={
                "db_table": "guest_account",
            },
        ),
    ]
