# Generated by Django 5.1.6 on 2025-04-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterviewData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "companyName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("question", models.TextField()),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "interview_question_data_per_job_category",
            },
        ),
    ]
