# Generated by Django 5.1.4 on 2025-05-06 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyDataTotal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=128)),
                ("est_date", models.CharField(max_length=20, null=True)),
                ("company_class", models.CharField(max_length=20, null=True)),
                ("ceo_name", models.CharField(max_length=50, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("website", models.URLField(null=True)),
                ("business_summary", models.TextField(null=True)),
                ("revenue_table", models.TextField(null=True)),
            ],
            options={
                "db_table": "company_data",
            },
        ),
        migrations.CreateModel(
            name="CompanyReport",
            fields=[
                (
                    "companyReportId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("companyReportName", models.CharField(max_length=128)),
                ("companyReportPrice", models.IntegerField()),
                ("companyReportCategory", models.CharField(max_length=128)),
                ("content", models.TextField()),
                ("keyword", models.CharField(max_length=255, null=True)),
                (
                    "companyReportTitleImage",
                    models.CharField(max_length=100, null=True),
                ),
                ("regDate", models.DateTimeField(auto_now_add=True)),
                ("updDate", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "company_report",
            },
        ),
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("revenue", models.BigIntegerField()),
                ("profit_trend", models.BigIntegerField()),
                ("owners_capital", models.BigIntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company_report.companydatatotal",
                    ),
                ),
            ],
            options={
                "db_table": "company_finance",
            },
        ),
    ]
