# Generated by Django 5.1.4 on 2025-04-28 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("review", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "review",
            },
        ),
        migrations.CreateModel(
            name="ReviewDescription",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                (
                    "review_id",
                    models.OneToOneField(
                        db_column="review_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.review",
                    ),
                ),
            ],
            options={
                "db_table": "review_description",
            },
        ),
        migrations.CreateModel(
            name="ReviewQuestion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=128)),
                ("question_type", models.CharField(max_length=10)),
                ("essential", models.BooleanField()),
                (
                    "review_id",
                    models.ForeignKey(
                        db_column="review_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.review",
                    ),
                ),
            ],
            options={
                "db_table": "review_question",
            },
        ),
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.TextField(null=True)),
                (
                    "question_id",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.reviewquestion",
                    ),
                ),
            ],
            options={
                "db_table": "review_image",
            },
        ),
        migrations.CreateModel(
            name="ReviewSelection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("selection", models.CharField(max_length=50)),
                (
                    "review_question_id",
                    models.ForeignKey(
                        db_column="review_question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.reviewquestion",
                    ),
                ),
            ],
            options={
                "db_table": "review_selection",
            },
        ),
        migrations.CreateModel(
            name="ReviewAnswer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("answer", models.CharField(max_length=128, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        db_column="account_id",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
                (
                    "survey_question_id",
                    models.ForeignKey(
                        db_column="survey_question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.reviewquestion",
                    ),
                ),
                (
                    "survey_selection_id",
                    models.ForeignKey(
                        db_column="survey_selection_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.reviewselection",
                    ),
                ),
            ],
            options={
                "db_table": "review_answer",
            },
        ),
        migrations.CreateModel(
            name="ReviewTitle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=64)),
                (
                    "review_id",
                    models.ForeignKey(
                        db_column="review_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.review",
                    ),
                ),
            ],
            options={
                "db_table": "review_title",
            },
        ),
    ]
