# Generated by Django 5.1.6 on 2025-03-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birthyear',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(default='Unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='loginType',
            field=models.CharField(default='Kakao', max_length=32),
        ),
        migrations.AlterField(
            model_name='accountroletype',
            name='roleType',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('NORMAL', 'Normal')], default='NORMAL', max_length=64),
        ),
    ]
