# Generated by Django 5.1.6 on 2025-03-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_birthyear_account_gender_account_logintype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthyear',
            field=models.IntegerField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='account',
            name='loginType',
            field=models.CharField(default='KAKAO', max_length=32),
        ),
    ]
