# Generated by Django 5.1.4 on 2025-04-21 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("Backend", "백엔드"),
                            ("Frontend", "프론트엔드"),
                            ("Embedded", "임베디드"),
                            ("AI", "인공지능"),
                            ("DevOps", "데비옵스"),
                            ("AppWeb", "웹앱"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "experience_level",
                    models.IntegerField(
                        choices=[
                            (1, "신입"),
                            (2, "3년 이하"),
                            (3, "5년 이하"),
                            (4, "10년 이하"),
                            (5, "10년 이상"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("IN_PROGRESS", "진행 중"), ("COMPLETED", "완료")],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "db_table": "interview",
            },
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="interview.interview",
                    ),
                ),
            ],
            options={
                "db_table": "interview_question_data",
            },
        ),
        migrations.CreateModel(
            name="InterviewAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interview.interview",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interview.interviewquestion",
                    ),
                ),
            ],
            options={
                "db_table": "interview_answer",
            },
        ),
    ]
