# Generated by Django 5.1.4 on 2025-03-28 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("interview_id", models.IntegerField()),
            ],
            options={
                "db_table": "interview",
            },
        ),
        migrations.CreateModel(
            name="InterviewFirstQuestion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "interview_first_question",
            },
        ),
        migrations.CreateModel(
            name="InterviewTechQuestion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=255)),
                ("job", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "interview_tech_question",
            },
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=255)),
                (
                    "interview_id",
                    models.ForeignKey(
                        db_column="interview_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interview.interview",
                    ),
                ),
            ],
            options={
                "db_table": "interview_question",
            },
        ),
    ]
