# Generated by Django 5.1.4 on 2025-05-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="academic_background",
            field=models.IntegerField(
                choices=[(1, "비전공자"), (2, "전공자")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="project_experience",
            field=models.IntegerField(choices=[(1, "없음"), (2, "있음")]),
        ),
    ]
