# Generated by Django 5.1.4 on 2025-05-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="tech_stack",
            field=models.JSONField(),
        ),
    ]
