# Generated by Django 5.1.4 on 2025-04-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="project_experience",
            field=models.IntegerField(choices=[(1, "있음"), (2, "없음")], default=2),
            preserve_default=False,
        ),
    ]
