# Generated by Django 5.1.4 on 2025-04-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InterviewData",
        ),
    ]
