# Generated by Django 5.1.4 on 2025-05-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0002_alter_interview_academic_background_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="interview_company",
            field=models.CharField(
                choices=[
                    ("danggeun", "당근마켓"),
                    ("toss", "Toss"),
                    ("sk_encore", "SK엔코아"),
                    ("kt_mobile", "KT모바일"),
                ],
                default="toss",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
