# Generated by Django 5.1.4 on 2025-04-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0002_interview_project_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="academic_background",
            field=models.IntegerField(
                choices=[(1, "전공자"), (2, "비전공자")], default=2
            ),
        ),
    ]
