# Generated by Django 5.1.6 on 2025-04-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0003_interview_academic_background"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="academic_background",
            field=models.IntegerField(
                choices=[(0, "비전공자"), (1, "전공자")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="project_experience",
            field=models.IntegerField(choices=[(0, "없음"), (1, "있음")]),
        ),
        migrations.AlterField(
            model_name="interview",
            name="topic",
            field=models.CharField(
                choices=[
                    (1, "Backend"),
                    (2, "Frontend"),
                    (3, "App·Web"),
                    (4, "AI"),
                    (5, "Embedded"),
                    (6, "DevOps"),
                ],
                max_length=50,
            ),
        ),
    ]
