# Generated by Django 5.1.4 on 2025-04-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0003_interview_academic_background"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewTechStack",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "인터뷰 기술스택",
                "verbose_name_plural": "인터뷰 기술스택 목록",
                "db_table": "interview_tech_stack",
            },
        ),
        migrations.AddField(
            model_name="interview",
            name="interview_tech_stack",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
