# Generated by Django 5.1.6 on 2025-04-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0004_alter_interview_academic_background_and_more"),
        ("interview", "0004_interviewtechstack_interview_interview_tech_stack"),
    ]

    operations = []
