# Generated by Django 5.1.4 on 2025-03-17 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountLoginType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loginType",
                    models.CharField(
                        choices=[
                            ("KAKAO", "Kakao"),
                            ("GOOGLE", "google"),
                            ("NAVER", "naver"),
                        ],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "account_login_type",
            },
        ),
        migrations.CreateModel(
            name="AccountProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=32, unique=True)),
                ("gender", models.CharField(default="Unknown", max_length=32)),
                ("birthyear", models.IntegerField(default="Unknown")),
                ("age_range", models.CharField(max_length=32)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "db_table": "account_profile",
            },
        ),
    ]
