# Generated by Django 5.1.4 on 2025-04-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountlogintype",
            name="loginType",
            field=models.CharField(
                choices=[
                    ("KAKAO", "Kakao"),
                    ("GOOGLE", "google"),
                    ("NAVER", "naver"),
                    ("GITHUB", "github"),
                    ("GUEST", "guest"),
                ],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
