# Generated by Django 5.1.4 on 2025-03-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_profile", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountprofile",
            old_name="account_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="accountprofile",
            old_name="profile_nickname",
            new_name="nickname",
        ),
    ]
