# Generated by Django 5.1.6 on 2025-03-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0003_adminprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
